version: '3'
services:  
  jenkins:    
    image: jenkins/jenkins:lts
    ports:      
      - 80:8080      
      - 50000:50000    
    volumes:      
      - "jenkins_data:/var/jenkins_home"

volumes:
  jenkins_data: